#!/bin/sh
# ONE PUBLISHER, AND IT IS THE DEFAULT BRANCH.
#
# WHY THIS EXISTS. `dist/latest.json`, `README.md` and `docs/index.html` are
# GENERATED by the publish step, from the version and from GITHUB_REF_NAME. The
# step ran on every branch, so a branch and main did not merely both write those
# files — they wrote DIFFERENT bytes into every line carrying a version or a
# ref:
#
#   main:   ".../MusicD-Share-Card/main/dist/musicd-share-card-0.51.0.apk"
#   branch: ".../MusicD-Share-Card/claude/sonos-.../dist/musicd-share-card-0.52.0.apk"
#
# So every pull request conflicted on all three, every release, and each one was
# resolved by hand. Reported as "this keeps happening". A conflict between two
# generators of the same file is not a merge going wrong; it is the design, and
# the only permanent fix is one writer.
#
# The branch build still compiles, signs and uploads the APK as an artifact.
# What it must not do is COMMIT a manifest — nothing reads a branch manifest
# (the app reads main's), and its url stops resolving the day the branch is
# deleted, which is a bug this repo has already shipped twice.
#
# Two things are asserted, and the second is the one that lasts: the publish
# step is gated on the default branch, AND nothing else in the workflow commits
# at all. A second publisher added later is the way this comes back.
set -eu

WORKFLOW="${1:-.github/workflows/build.yml}"
fail=0

say() { printf '%s\n' "$*"; }
bad() { printf 'FAIL %s\n' "$*"; fail=1; }

[ -f "$WORKFLOW" ] || { say "cannot find $WORKFLOW"; exit 1; }

# The gate. Both halves: a push (not a pull_request build, which has no business
# committing) and the repository's own default branch (not a hardcoded name).
gate=$(awk '
  /- name: Publish the APK into dist\/$/ { step = 1; next }
  step && /^        (run|env):/          { exit }
  step                                   { print }
' "$WORKFLOW")

if [ -z "$gate" ]; then
  bad "there is no step named \"Publish the APK into dist/\" — if it was renamed,
     rename it here too rather than deleting this check"
else
  case "$gate" in
    *"github.ref_name == github.event.repository.default_branch"*)
      say "ok   the publish step runs only on the default branch" ;;
    *)
      bad "the publish step is not gated on the default branch. It generates
     dist/latest.json, README.md and docs/index.html from GITHUB_REF_NAME, so a
     second branch writing them means a conflict in all three on every pull
     request — which is exactly what this check was added after." ;;
  esac
  case "$gate" in
    *"github.event_name == 'push'"*)
      say "ok   and only on a push" ;;
    *)
      bad "the publish step must be gated on a push event" ;;
  esac
fi

# And nothing else commits. `git commit` anywhere outside that step is a second
# writer of tracked files, which is how this comes back wearing another name.
commits=$(grep -n 'git commit' "$WORKFLOW" | grep -v 'git commit -q -m "Publish' || true)
if [ -n "$commits" ]; then
  bad "something other than the publish step commits to the repository:
$commits"
else
  say "ok   nothing else in the workflow commits"
fi

# The generated files are named here so that adding a fourth without thinking
# about this rule is awkward rather than silent.
for f in dist/latest.json README.md docs/index.html; do
  grep -q "$(basename "$f")" "$WORKFLOW" || bad "$f is no longer written by the workflow — is this check still describing it?"
done

if [ "$fail" -ne 0 ]; then
  printf '\npublish checks FAILED.\n'
  exit 1
fi
printf '\npublish checks passed.\n'
